
spring:
  application:
    name: order-service
  config:
    import: "optional:configserver:http://localhost:9199"
  datasource:
    password: 654321
    url: jdbc:mysql://localhost:3306/order_db?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  boot:
    admin:
      client:
        url:
        - http:localhost:9200

management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include:
        - "*"
  info:
    env:
      enabled: true