
spring:
  application:
    name: product-service
  config:
    import: "optional:configserver:http://localhost:9199"
  data:
    jpa:
      repositories:
        enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/product-service?createDatabaseIfNotExist=true
    password: 654321
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
    properties:
      hibernate:
        format: true
    show-sql: true
  boot:
    admin:
      client:
        url:
        - http://localhost:9200
  jackson:
    default-property-inclusion: non-null
 # proprties zipkin and admin        
management:
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include:
        - "*"
  info:
    env:
      enabled: true
     #=============swagger 
springdoc:
  api-docs:
    enabled: true
    path: /api-docs
  swagger-ui:
    enabled: true   
    path: swagger-ui-product.html
    operations-sorter: method

  
  
 