
spring:
  application:
    name: idantity-service
  config:
    import: "optional:configserver:http://localhost:9199"
  datasource:
    password: 654321
    url: jdbc:mysql://localhost:3306/idantity_service?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  main:
    allow-circular-references: true

management:
  tracing:
    sampling:
      probability: 1.0